spring:
  application:
    name: gateway

server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-6001
    prefer-ip-address: true

zuul:
  routes:
    user:
      serviceId: provider
      path: /user/**